import React,{useEffect,useMemo,useState} from 'react';
import { useParams,useSearchParams,Link } from 'react-router-dom';
import {SlidersHorizontal,Search} from 'lucide-react';
import SiteShell from '../components/SiteShell.jsx';
import ProductGrid from '../components/ProductGrid.jsx';
import { allProducts,categories } from '../data/catalog.js';
import useAdminRows from '../hooks/useAdminRows.js';
export default function CatalogPage(){
 const {type}=useParams(); const [params]=useSearchParams(); const [q,setQ]=useState(params.get('q')||''); const [sort,setSort]=useState('featured'); const [brand,setBrand]=useState('all');
 useEffect(()=>setQ(params.get('q')||''),[params]);
 const adminProducts=useAdminRows('Products',[]); const adminCategories=useAdminRows('Categories',[]);
 const source=adminProducts.length?adminProducts.filter(x=>x.status==='Active').map(x=>({id:x.id,name:x.name,image:x.image,saving:x.saving||'0',price:String(x.value||x.price||'0'),discount:x.discount||'0%',rating:x.rating||'4.5',mrp:x.mrp||x.value||'0',category:x.category||x.notes||'Phones',brand:x.brand||'Other',condition:x.condition||'Refurbished',stock:x.stock??0,description:x.description||'',assured:x.assured})):allProducts;
 const normalized=type==='all'?null:type; const title=type==='laptops'?'Refurbished Laptops':type==='phones'?'Refurbished Phones':type&&type!=='all'?`${type[0].toUpperCase()+type.slice(1)} Devices`:'Buy Refurbished Devices';
 const brands=[...new Set(source.map(p=>p.brand).filter(Boolean))]; const liveCategories=adminCategories.length?adminCategories.filter(x=>x.status==='Active').map(x=>({name:x.name,slug:x.slug||x.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')})):categories;
 const items=useMemo(()=>{let a=source.filter(p=>!normalized||p.category.toLowerCase()===normalized);if(q){const term=q.toLowerCase();a=a.filter(p=>(`${p.name} ${p.brand} ${p.category}`).toLowerCase().includes(term))}if(brand!=='all')a=a.filter(p=>p.brand===brand);const num=x=>Number(String(x).replace(/,/g,''))||0;if(sort==='price-low')a=[...a].sort((x,y)=>num(x.price)-num(y.price));if(sort==='price-high')a=[...a].sort((x,y)=>num(y.price)-num(x.price));if(sort==='rating')a=[...a].sort((x,y)=>Number(y.rating)-Number(x.rating));return a;},[source,normalized,q,sort,brand]);
 return <SiteShell><section className="container page-hero catalog-hero"><div><p className="eyebrow">Certified refurbished</p><h1>{title}</h1><p>Quality-checked devices, transparent pricing, warranty support and secure checkout.</p></div></section><section className="container category-chips">{liveCategories.map(c=><Link className={type===c.slug?'active':''} to={`/buy/${c.slug}`} key={c.slug}>{c.name}</Link>)}</section><section className="container page-section"><div className="catalog-toolbar"><div className="catalog-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products, model or brand"/></div><select value={brand} onChange={e=>setBrand(e.target.value)}><option value="all">All brands</option>{brands.map(b=><option key={b}>{b}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="price-low">Price: Low to High</option><option value="price-high">Price: High to Low</option><option value="rating">Top Rated</option></select><span className="result-count"><SlidersHorizontal size={16}/>{items.length} results</span></div>{items.length?<ProductGrid items={items}/>:<div className="empty-state"><h2>No products found</h2><p>Try a different product, brand or category.</p><button className="secondary-btn" onClick={()=>{setQ('');setBrand('all')}}>Clear filters</button></div>}</section></SiteShell>
}
