import React,{useMemo,useState} from 'react';
import {QRCodeSVG} from 'qrcode.react';
import {Link,useNavigate} from 'react-router-dom';
import {load,save} from '../utils/localStore.js';
import {claimCoupon,upsertModuleRecord} from '../services/store.js';
import useAdminRows from '../hooks/useAdminRows.js';
import {useAuth} from '../context/AuthContext.jsx';
const defaultCoupon={id:'SEQ88',code:'SEQ88',name:'SEQ88',status:'Active',discountType:'percentage',discountValue:88,claimLimit:10,perUserLimit:1,usedCount:0};
export default function CheckoutPage(){
 const nav=useNavigate(),{user}=useAuth(); const cart=load('cart',[]); const raw=cart.length?cart.reduce((s,x)=>s+parseInt(String(x.price).replace(/,/g,''))*x.qty,0):10000;
 const coupons=useAdminRows('Coupons',[defaultCoupon]); const settings=useAdminRows('Website Settings',[{id:'upi',name:'UPI ID',status:'Active',value:'subhamdebasish225@okicici'},{id:'payee',name:'UPI Payee Name',status:'Active',value:'OneTap Cashify'}]);
 const [code,setCode]=useState(''),[coupon,setCoupon]=useState(null),[couponError,setCouponError]=useState(''),[address,setAddress]=useState({name:user?.name||'',phone:'',email:user?.email||'',line:'',city:'',state:'',pin:''}),[utr,setUtr]=useState('');
 const discount=useMemo(()=>{if(!coupon)return 0;const val=Number(coupon.discountValue??coupon.value??0);return coupon.discountType==='fixed'?Math.min(raw,val):Math.round(raw*val/100)},[coupon,raw]); const total=Math.max(0,raw-discount);
 const findSetting=(name,fallback)=>settings.find(x=>x.status==='Active'&&x.name===name)?.value||fallback; const upi=findSetting('UPI ID','subhamdebasish225@okicici'),payee=findSetting('UPI Payee Name','OneTap Cashify'); const [order]=useState(()=>`ORD${Date.now().toString().slice(-8)}`); const uri=useMemo(()=>`upi://pay?pa=${encodeURIComponent(upi)}&pn=${encodeURIComponent(payee)}&am=${total.toFixed(2)}&cu=INR&tn=${encodeURIComponent(order)}`,[upi,payee,total,order]);
 const apply=()=>{const normalized=code.trim().toUpperCase();const c=coupons.find(x=>(x.code||x.name||x.id||'').toUpperCase()===normalized&&x.status==='Active');if(!c){setCoupon(null);setCouponError('Invalid or inactive coupon code.');return;}const claims=load('couponClaims',{});const entry=claims[normalized]||{total:0,users:{}};const userKey=user?.uid||address.email||address.phone||'guest-device';if(Number(c.claimLimit||0)>0&&(Number(c.usedCount||0)>=Number(c.claimLimit)||entry.total>=Number(c.claimLimit))){setCouponError('This coupon has reached its claim limit.');return;}if((entry.users?.[userKey]||0)>=Number(c.perUserLimit||1)){setCouponError('You have already used this coupon.');return;}setCoupon(c);setCouponError('')};
 const place=async()=>{if(!address.name||!address.phone||!address.line||!address.pin)return alert('Please complete delivery details');try{if(coupon){const userKey=user?.uid||address.email||address.phone||'guest-device';await claimCoupon(coupon.code||coupon.name,userKey)}const orders=load('orders',[]);const rec={id:order,name:address.name,status:utr?'Payment Submitted':'Payment Pending',value:`₹${total.toLocaleString('en-IN')}`,total:total.toLocaleString('en-IN'),date:new Date().toLocaleDateString(),address,utr,coupon:coupon?.code||coupon?.name||null,items:cart,notes:utr?`UTR: ${utr}`:'Awaiting UPI payment'};orders.unshift(rec);save('orders',orders);await upsertModuleRecord('Orders',{...rec,userId:user?.uid||null,email:address.email||''});const payment={id:`PAY-${order}`,name:address.name,status:utr?'Payment Submitted':'Pending',value:`₹${total.toLocaleString('en-IN')}`,notes:utr?`UPI ${upi} • UTR ${utr}`:`UPI ${upi} • Awaiting UTR`,orderId:order,userId:user?.uid||null,email:address.email||''};await upsertModuleRecord('Payments',payment);save('cart',[]);nav('/order-success',{state:{orderId:order}})}catch(e){alert(e.message||'Unable to place order.')}};
 return <div className="checkout-page"><div className="checkout-shell"><div className="checkout-main"><Link to="/cart">← Back to cart</Link><h1>Checkout</h1><section className="checkout-section"><h2>Delivery details</h2><div className="form-grid">{[['name','Full Name'],['phone','Mobile'],['email','Email'],['line','Address'],['city','City'],['state','State'],['pin','PIN Code']].map(([k,l])=><input key={k} placeholder={l} value={address[k]} onChange={e=>setAddress({...address,[k]:e.target.value})}/>)}</div></section><section className="checkout-section"><h2>Apply offer</h2><div className="coupon-row"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Offer code"/><button onClick={apply}>Apply</button></div>{coupon&&<p className="success-text">{coupon.code||coupon.name} applied — {coupon.discountType==='fixed'?`₹${coupon.discountValue}`:`${coupon.discountValue??coupon.value}%`} discount</p>}{couponError&&<p className="coupon-error">{couponError}</p>}</section><section className="checkout-section"><h2>UPI Payment</h2><div className="qrbox"><h3>Scan & Pay ₹{total.toLocaleString('en-IN')}</h3><QRCodeSVG value={uri} size={210}/><p><b>UPI:</b> {upi}</p><p><b>Order:</b> {order}</p><a className="upi-button" href={uri}>Pay Using UPI App</a><input value={utr} onChange={e=>setUtr(e.target.value)} placeholder="Enter UTR / Transaction ID after payment"/></div></section></div><aside className="summary-card checkout-summary"><h3>Order Summary</h3><p><span>Subtotal</span><b>₹{raw.toLocaleString('en-IN')}</b></p><p><span>Coupon {coupon?.code||coupon?.name||''}</span><b>-₹{discount.toLocaleString('en-IN')}</b></p><p><span>Delivery</span><b>FREE</b></p><hr/><p className="grand"><span>Final Amount</span><b>₹{total.toLocaleString('en-IN')}</b></p><button className="primary-btn block" onClick={place}>Place Order</button><small>Payment remains pending until verified by admin.</small></aside></div></div>
}
