import React from 'react'; import SiteShell from '../components/SiteShell.jsx'; import SafeImage from '../components/SafeImage.jsx'; import {ShieldCheck,RefreshCcw,LockKeyhole,Building2,Mail,Phone} from 'lucide-react';
const content={
 about:{h:'About Us',p:'A trusted marketplace experience for selling used devices, buying refurbished products and accessing device services.',icon:Building2,sections:[['What we do','We bring selling, buying, repair and support flows into one responsive experience. Products are presented with clear pricing, condition information and quality assurances.'],['Our approach','The customer experience focuses on transparent information, responsive layouts, secure checkout and consistent after-sales support.']]},
 contact:{h:'Contact Us',p:'Reach support for orders, payments, selling, stores or repair requests.',icon:Mail,sections:[['Customer Support','Email: onetapcashify@gmail.com\nPhone: +91 9621956411'],['Working Hours','Monday to Saturday, 9:00 AM to 7:00 PM.']]},
 faq:{h:'Help & FAQs',p:'Answers related to selling, buying, payments, warranty, replacement and service requests.',icon:Phone,sections:[['Buying','Check product condition, warranty, price and stock before ordering.'],['Payments','UPI payment stays pending until transaction details are submitted and verified.'],['Selling','Estimated values are confirmed after device verification.']]},
 terms:{h:'Terms & Conditions',p:'These terms explain use of the marketplace, orders, payments and service requests.',icon:ShieldCheck,sections:[['Orders','Orders are subject to product availability, payment verification and serviceable delivery locations.'],['Payments','Customers should verify the final payable amount before completing a transaction.']]},
 privacy:{h:'Privacy Policy',p:'This page explains how customer and order information is handled in this site template.',icon:LockKeyhole,sections:[['Information','Account, address and order information is used to provide requested services.'],['Security','Administrative access and customer data should be protected using Firebase Authentication and security rules in production.']]},
 warranty:{h:'Warranty',p:'Warranty coverage depends on the product or service shown at the time of purchase.',icon:ShieldCheck,sections:[['Coverage','Eligible refurbished devices may include limited warranty support for covered functional issues.'],['Exclusions','Accidental or physical damage and unauthorized repair may be excluded depending on the stated policy.']]},
 returns:{h:'Returns & Replacement',p:'Review eligibility and raise a support request if an eligible device needs replacement.',icon:RefreshCcw,sections:[['Eligibility','Replacement eligibility depends on the stated replacement period and product condition.'],['Process','Keep order details, packaging and device information ready when contacting support.']]}
};
export default function InfoPage({kind='about'}){const c=content[kind]||content.about; const Icon=c.icon; return <SiteShell><section className="container page-hero media-hero"><div><p className="eyebrow">Information</p><h1>{c.h}</h1><p>{c.p}</p></div><SafeImage src="https://s3n.cashify.in/builder/4060695bca3447c2b7296aa5ba9ce827.webp" alt={c.h}/></section><section className="container legal-copy info-rich"><div className="info-heading"><Icon/><div><h2>{c.h}</h2><p>{c.p}</p></div></div>{c.sections.map(([h,p])=><section key={h}><h3>{h}</h3>{p.split('\n').map(x=><p key={x}>{x}</p>)}</section>)}</section></SiteShell>}
